global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitriy_erokhin'
