version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      - back-net
  ui:
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front-net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - back-net
      - front-net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back-net
      - front-net

volumes:
  post_db:

networks:
  front-net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back-net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
