version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:5.6
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:5.6
    ports:
      - "5601:5601"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - back-net
      - front-net

networks:
  front-net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back-net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
